### ISSUE TITLE
Is it possible to save List<Geometry> data to file or playerpref ?

### ISSUE THREAD

**Issue by superbderrick** [Unity-Technologies/vector-graphics-samples#27]
Hi Unity forks,

Thanks for making a good vector package

We have released an app using that the vector packages , Really thanks

App link : https://apps.apple.com/us/app/baby-shark-coloring-book/id1286586207

What I am curious about is when I move from the normal screen to the drawing screen,

We currently have the following routine:

1.Download the svg image file from the server,
2.SVG import it, and
3.Create a spirte after tessellation

The image used is usually 1024 * 1024 size.

During this process, it is very slow on low-end Android phones

`var geoms = VectorUtils.TessellateScene(sceneInfo.Scene, tessOptions);`

This is what I'm curious about , Is there a way to save the List<Geometry> data to a file?

var geoms = VectorUtils.TessellateScene(sceneInfo.Scene, tessOptions)

 I want to reduce the eroutine repeatedly.

Any help would be greatly appreciated

**Comment by Antonio-Iliev** [comment]
Hi Derrick,
Cool game! :)
I also read that process is slower. Can you serialise the Geometry object, send it like a data file, and deserialise? Instead of relying on the Tesselation. This suggestion is just shouting in the dark. Or you can offload the work to the server and retrieve the Sprite object.

**Comment by superbderrick** [comment]
@Antonio-Iliev 
Thanks for the reply, I thought so too at the first time as a Geometry object, to save data to a file and read it, but the API is like that cannot be serialized. It didn’t have a serialized field and contained uicolor vslue, it might disturb to do serializtion and the node value is very large, it is not easy to save it. I will approach it in a server open load method :)
Thanks :) good care!!

**Comment by mcoted** [comment]
The Geometry struct wasn't designed to be serializable, especially because it contains an IFill interface, which is polymorphic.

You could try to make a copy of the Geometry values inside your own serializable struct and serialize/deserialize that instead, but you'll have issues with the fill values as mentioned above. This may or may not be a problem for your situation.

Alternatively, you can try to serialize the resulting Sprite object that you created from the geometry list.

**Comment by superbderrick** [comment]
Thanks, Let me try :) Good care Martin :)
